version: "3"

services:
  age-detection:
    container_name: age-detector
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./data/age_prediction:/app/data
      - ./dev:/app
      - /dev/video0:/dev/video0
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]